In [2]:
#numpy - numerical python and it's a fundamental package for scientific computing in Python. NumPy provides 
#Python with an extensive math library capable of performing numerical computations effectively and efficiently. 
import numpy as np
import time

In [4]:
x = np.random.random(100000000)
#print(x)

In [5]:
start = time.time()
sum(x)/len(x)
print(time.time() - start)  #normal python took 7.44 seconds to complete the mean of 100000000 random values

7.44398307800293


In [6]:
start1 = time.time()
np.mean(x)
print(time.time() - start1) #numpy took approximately 0.1 second to complete the above transaction

0.1293492317199707


In [9]:
y = np.array([1,2,4,4,56,5]) #ndarray (n dimensional array creation using the array function and giving list as i/p)
print(y) 
print(type(y)) #gives the type of y 
print(y.dtype) #gives the type of all elements in ndarray y
print(y.shape) #give the number of columns in ndarray if it is 1 dimensional
print(y.size)  #gives the total number of elements in ndarray

[ 1  2  4  4 56  5]
<class 'numpy.ndarray'>
int32
(6,)
6


In [12]:
z = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]]) #two dimensional array -rank2 array
print(z)
print(z.shape) #gives the total number of rows, columns
print(z.size)  #gives the total number of elements in array

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]
(4, 3)
12


In [13]:
a = np.array(['hello','world'])
print(a)
print('shape', a.shape)
print('type', type(a))
print('dtype',a.dtype)  #numpy creates an array it automatically assign it's dtype based on the elements you used
#to create an array. Here it is unicode strings with 5 characters

['hello' 'world']
shape (2,)
type <class 'numpy.ndarray'>
dtype <U5


In [14]:
b = np.array([1,3.5,4,'hello','world']) #list contains mixed data types
print(b)
print('shape', b.shape)
print('type', type(b))
print('dtype',b.dtype)  #numpy creates an array it automatically assign it's dtype based on the elements you used
#to create an array. Here it is unicode strings with 32 characters. Unlike python lists numpy arrays must contain 
#elements of the same data type

['1' '3.5' '4' 'hello' 'world']
shape (5,)
type <class 'numpy.ndarray'>
dtype <U32


In [16]:
c = np.array([1,2,3.4,5])
print(c)
print('dtype',c.dtype)#upcasting-all integers to float data type to avoid losing precision in numerical operations

[1.  2.  3.4 5. ]
dtype float64


In [4]:
d = np.array([2.3,4,5.6,7.89], dtype=np.int64) #trying to create ndarray by passing dtype as int64
print(d) #creates only integers as elements in the array as we have passed dtype = np.int64

[2 4 5 7]


In [5]:
e = np.array([1,2,3,4,5])
np.save('my_array',e) #this saves the numpy array in my_array.npy file in the current directory
f = np.load('my_array.npy') #this loads the data from file my_array.npy to array f
print(f)

[1 2 3 4 5]


In [8]:
#Use builtin functions to create ndarrays----function 'zeros'
f = np.zeros((3,4)) #tuple (3,4) represents 3 rows and 4 columns with values zeros
print(f)
print('type', type(f))
print('dtype',f.dtype) #it creates an array with default dtype as float64
print('shape',f.shape)
print('size',f.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
type <class 'numpy.ndarray'>
dtype float64
shape (3, 4)
size 12


In [10]:
#functions 'ones'
g = np.ones((3,4),dtype=np.int) #tuple (3,4) represents 3 rows and 4 columns with values zeros
print(g)
print('type', type(g))
print('dtype',g.dtype) #it creates an array with default dtype as float64
print('shape',g.shape)
print('size',g.size)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
type <class 'numpy.ndarray'>
dtype int32
shape (3, 4)
size 12


In [79]:
#In addition to ones and zeros, we can create an array filled with any constant values using 'full' function
h = np.full((3,4),5) #tuple (3,4) represents 3 rows and 4 columns with values zeros and this function defaultly 
#creates the dtype of the array with argument datatype here it is 5 ->int32
print(h)
print('type', type(h))
print('dtype',h.dtype) #it creates an array with default dtype as float64
print('shape',h.shape)
print('size',h.size)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
type <class 'numpy.ndarray'>
dtype int32
shape (3, 4)
size 12


In [14]:
#function 'eye' used to create identity matrices (square) and takes only one argument of shape
i = np.eye(5) # it creates 5 X 5 identity matrix
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
#function 'diag' used to create a diagonal square matrix with the passing values
j = np.diag([10,20,30,40])
print(j)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [80]:
#function 'arange' used to create rank 1 array with the argument start, stop, step
k = np.arange(10) #stop argument
print(k)
l = np.arange(10,20) #start , stop arguments
print(l)
m = np.arange(10,20,2) #start, stop, step arguments
print(m)
n = np.arange(1,5,0.5)
print(n)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [19]:
#Even though the np.arange() function allows for non-integer steps, such as 0.3, the output is usually 
#inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps 
#are required, it is usually better to use the function np.linspace(). The np.linspace(start, stop, N) function 
#returns N evenly spaced numbers over the closed interval [start, stop]. This means that both the start and 
#the stop values are included. We should also note the np.linspace() function needs to be called with at least 
#two arguments in the form np.linspace(start,stop). In this case, the default number of elements in the specified 
#interval will be N= 50. The reason np.linspace() works better than the np.arange() function, is that 
#np.linspace() uses the number of elements we want in a particular interval, instead of the step between values. 
o = np.linspace(10,20,10) #here 10, 20 both are inclusive and it gives 10 equally spaced values
print(o)
print('o has dimensions:', o.shape)
print('o is an object of type:', type(o))
print('The elements in o are of type:', o.dtype)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]
o has dimensions: (10,)
o is an object of type: <class 'numpy.ndarray'>
The elements in o are of type: float64


In [22]:
#if you want to exclude end value similar to arange function use endpoint = False in linspace function
p = np.linspace(10,20,10, endpoint = False) #here 10 is inclusive and 20 is exclusive and it gives 10 equally spaced values
print(p) #value 20 got excluded
print('p has dimensions:', p.shape)
print('p is an object of type:', type(p))
print('The elements in p are of type:', p.dtype)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
p has dimensions: (10,)
p is an object of type: <class 'numpy.ndarray'>
The elements in p are of type: float64


In [25]:
# np.reshape(ndarray, new_shape) function converts the given ndarray into the specified new_shape. It is important 
#to note that the new_shape should be compatible with the number of elements in the given ndarray
q = np.arange(20)
print('original array:', q)
q = np.reshape(q, (4,5))
print('reshaped array\n', q)
print('q has dimensions:', q.shape)
print('q is an object of type:', type(q))
print('The elements in q are of type:', q.dtype)

original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
reshaped array
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
q has dimensions: (4, 5)
q is an object of type: <class 'numpy.ndarray'>
The elements in q are of type: int32


In [26]:
#One great feature about NumPy, is that some functions can also be applied as methods. This allows us to apply 
#different functions in sequence in just one line of code. ndarray methods are similar to ndarray attributes in 
#that they are both applied using dot notation (.).
r = np.arange(20).reshape(4,5)
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
#create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
s = np.linspace(0,50,10, endpoint = False).reshape(5,2)
print(s)
print('s has dimensions:', s.shape)
print('s is an object of type:', type(s))
print('The elements in s are of type:', s.dtype)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]
s has dimensions: (5, 2)
s is an object of type: <class 'numpy.ndarray'>
The elements in s are of type: float64


In [4]:
#The last type of ndarrays we are going to create are random ndarrays. Random ndarrays are arrays that contain 
#random numbers. Often in Machine Learning, you need to create random matrices, for example, when initializing 
#the weights of a Neural Network. NumPy offers a variety of random functions to help us create random ndarrays 
#of any shape.
t = np.random.random((3,3))#create a 3 x 3 ndarray with random floats in the half-open interval (0.0, 1.0)
print(t)
print('t has dimensions:', t.shape)
print('t is an object of type:', type(t))
print('The elements in t are of type:', t.dtype)

[[0.45499937 0.05176867 0.41523862]
 [0.72125371 0.58353108 0.06239369]
 [0.94589021 0.82939963 0.35165199]]
t has dimensions: (3, 3)
t is an object of type: <class 'numpy.ndarray'>
The elements in t are of type: float64


In [8]:
#NumPy also allows us to create ndarrays with random integers within a particular interval. The function 
#np.random.randint(start, stop, size = shape)
u = np.random.randint(4,15, size=(3,2)) #creates an ndarray of the given shape with random integers in the 
#half-open interval [start, stop)
print(u)
print('u has dimensions:', u.shape)
print('u is an object of type:', type(u))
print('The elements in u are of type:', u.dtype)

[[10  9]
 [ 4 11]
 [ 4  9]]
u has dimensions: (3, 2)
u is an object of type: <class 'numpy.ndarray'>
The elements in u are of type: int32


In [34]:
#In some cases, you may need to create ndarrays with random numbers that satisfy certain statistical properties. 
#For example, you may want the random numbers in the ndarray to have an average of 0. NumPy allows you create 
#random ndarrays with numbers drawn from various probability distributions. The function 
#np.random.normal(mean, standard deviation, size=shape), for example, creates an ndarray with the given shape 
#that contains random numbers picked from a normal (Gaussian) distribution with the given mean and standard 
#deviation. Let's create a 1,000 x 1,000 ndarray of random floating point numbers drawn from a normal distribution 
#with a mean (average) of zero and a standard deviation of 0.1.
v = np.random.normal(0, 0.1, size=(1000,1000))
print(v)
print('v has dimensions:', v.shape)
print('v is an object of type:', type(v))
print('The elements in v are of type:', v.dtype)
print('The elements in v have a mean of:', v.mean())
print('The maximum value in v is:', v.max())
print('The minimum value in v is:', v.min())
print('v has', (v < 0).sum(), 'negative numbers')
print('v has', (v > 0).sum(), 'positive numbers')

[[ 0.02533328 -0.03672482 -0.04571919 ...  0.00180402 -0.07859781
  -0.08048677]
 [ 0.0107391  -0.12547036  0.01708447 ... -0.02446352 -0.10781304
   0.05492889]
 [-0.04081266  0.00048142 -0.09090761 ... -0.02184834  0.039774
   0.07433315]
 ...
 [ 0.21220804  0.18047308 -0.09593706 ... -0.02033013  0.0429093
  -0.11549667]
 [ 0.01271948 -0.09842016 -0.09449699 ... -0.08693998  0.03987904
   0.19785871]
 [ 0.03741471  0.10490071  0.00703629 ... -0.02882438 -0.17069814
   0.19266988]]
v has dimensions: (1000, 1000)
v is an object of type: <class 'numpy.ndarray'>
The elements in v are of type: float64
The elements in v have a mean of: 4.901937533554252e-05
The maximum value in v is: 0.4880229750868906
The minimum value in v is: -0.46599346705459094
v has 499484 negative numbers
v has 500516 positive numbers


In [40]:
#create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive)
w = np.arange(2,33,2).reshape(4,4)
print('w:\n',w)
x1 = np.linspace(2,32,16,dtype=np.int32).reshape(4,4)
print('x1:\n',x1)


w:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
x1:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [42]:
#Accessing, Deleting, and Inserting Elements Into ndarrays -numpy arrays are mutable
a1 = np.array([1,2,3,4,5])
print(a1)
print('first element :', a1[0]) #using positive indices
print('second element:', a1[1])
print('fifth element :', a1[4])
print('first element :', a1[-5]) #using negative indices
print('second element:', a1[-4])
print('fifth element :', a1[-1])

[1 2 3 4 5]
first element : 1
second element: 2
fifth element : 5
first element : 1
second element: 2
fifth element : 5


In [43]:
#modifying the data in array a1
a1[3] = 24 #changing the element at index 3 or at fourth position which is 4 to 24
print(a1)


[ 1  2  3 24  5]


In [46]:
#for rank2 arrays, we need to provide indices with comma
b1 = np.arange(1,10).reshape(3,3)
print(b1)
print('element at (0,0):', b1[0,0])
print('element at (0,1):', b1[0,1])
print('element at (2,2):', b1[2,2])
#modifying the data in rank2 array
b1[0,0] = 22
print(b1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
element at (0,0): 1
element at (0,1): 2
element at (2,2): 9
[[22  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [50]:
#deleting elements from ndarrays
c1 = np.array([1,2,3,4,5,6,7]) #rank1 array
print('original:',c1)
c1 = np.delete(c1, [0,6]) #delete the first and last elements from the array c1
print('deleted:',c1)

original: [1 2 3 4 5 6 7]
deleted: [2 3 4 5 6]


In [54]:
d1 = np.arange(1,10).reshape(3,3)
print('original:\n', d1)

e1 = np.delete(d1, 0, axis=0) #delete the first row , axis argument required for rank2 arrays
print('row deleted:\n',e1)

f1 = np.delete(d1, [0,2], axis=1) #delete first and last columns of the array d1. axis=1 :coulmn, axis=0: row
print('columns deleted:\n',f1)

original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
row deleted:
 [[4 5 6]
 [7 8 9]]
columns deleted:
 [[2]
 [5]
 [8]]


In [58]:
#we can add elements to the ndarray with append function similar to list. 
g1 = np.array([1,2,3,4,5])
print(g1)
g1 = np.append(g1,6) #adding one element
print(g1)
g1 = np.append(g1,[7,8,9,10]) #adding 4 elements
print(g1)


[1 2 3 4 5]
[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10]


In [82]:
h1 = np.arange(1,10).reshape(3,3)
print(h1)
i1 = np.append(h1, [[10,11,12]], axis=0) #adding one row of elements to 3X3 matrix
print(i1)
j1 = np.append(i1, [[13],[14],[15],[16]], axis=1) #adding a new column of elements to 4 X3 matrix
print(j1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]
 [10 11 12 16]]


In [69]:
#insert  - using insert function and it takes index, elements and axis
k1 = np.array([1,2,5,6,7]) #insert elements 3 and 4 between 2 and 5 using insert function
print(k1)
k1 = np.insert(k1,2,[3,4])
print(k1)

[1 2 5 6 7]
[1 2 3 4 5 6 7]


In [75]:
l1 = np.array([[1,2,3],[7,8,9]]) #rank2 array
print(l1)
l1 = np.insert(l1, 1, [4,5,6],axis=0)#insert at first row using axis=0
print(l1)
l1 = np.insert(l1, 3, [10,11,12],axis=1)
print(l1)

[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [79]:
#we can stack one array on top of another array or side by side stacking which are having the same shapes using 
#vstack for vertical stacking and hstack for horizontal stacking
m1 = np.array([1,2])
print(m1)
n1 = np.array([[3,4],[5,6]])
print(n1)
o1 = np.vstack((m1,n1))
print(o1)

p1 = np.hstack((n1, m1.reshape(2,1)))
print(p1)

[1 2]
[[3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[3 4 1]
 [5 6 2]]


In [83]:
#slicing of ndarrays -access the subsets of NumPy arrays with slicing
# 1. ndarray[start : end] starting index inclusive and ending index is exclusive
# 2. ndarray[start : ] starting index to last element
# 3. ndarray[ : end] from begining to last index -1 

q1 = np.arange(1,21).reshape(4,5)
print('q1\n',q1)

r1 = q1[1:4, 2:5] #rows indices, column indices
print('r1\n',r1)

s1 = q1[1: , 2:]
print('s1\n',s1)

t1 = q1[ :3, 2:]
print('t1\n',t1)

u1 = q1[:, 2] #all rows values from 3rd columns which has index of 2
print('u1\n',u1)

v1 = q1[:, 2:3] #converts into rank2 array
print('v1\n', v1)

q1
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
r1
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]
s1
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]
t1
 [[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
u1
 [ 3  8 13 18]
v1
 [[ 3]
 [ 8]
 [13]
 [18]]


In [84]:
#sliciing doesn't copy the data from one array to other, it just a view of the same array with the specified
#slicing. If you change anything in the sliced array that will effect the original array also. So, if we want to 
#copy the data from one array to other you need to use numpy's copy function
print(q1)
w1 = q1[1:,2:]
print(w1)
w1[2,2] = 1000
print(w1) #value at 2,2 of w1 changed to 1000
print(q1) #above change effects the original array

x1 = q1[1:,2:].copy() #using this .copy() function creates a completely new numPy array that is independent of original
print(x1)
x1[2,2] = 20
print(x1)
print(q1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[   8    9   10]
 [  13   14   15]
 [  18   19 1000]]
[[   1    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19 1000]]
[[   8    9   10]
 [  13   14   15]
 [  18   19 1000]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[   1    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19 1000]]


In [85]:
indices = np.array([1,3])
print(indices)
print(q1)
y1 = q1[indices, :]
print(y1)

z1 = q1[:, indices]
print(z1)

[1 3]
[[   1    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19 1000]]
[[   6    7    8    9   10]
 [  16   17   18   19 1000]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [22]:
print(q1)
a2 = np.diag(q1) #extracts the diagonal elements of an array q1 -here default value of k is 0
print(a2)
b2 = np.diag(q1, k=1) #gets the elements above the main diagonal elements
print(b2)
c2 = np.diag(q1, k=-1) #gets the elements below the main diagonal elements
print(c2)

[[   1    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19 1000]]
[ 1  7 13 19]
[   2    8   14 1000]
[ 6 12 18]


In [26]:
# using np.unique function, we can extract the unique elements in a numpy array
d2 = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(d2)
print(np.unique(d2))

[[1 2 3]
 [2 3 4]
 [3 4 5]]
[1 2 3 4 5]


In [37]:
#Boolean indexing, Set operations and sorting
#suppose we have a 10,000 x 10,000 ndarray of random integers ranging from 1 to 15,000 and we only want to 
#select those integers that are less than 20. Boolean indexing can help us in these cases, by allowing us select 
#elements using logical arguments instead of explicit indices
e2 = np.arange(25).reshape(5,5)
print(e2)
print('\n',e2[e2>10]) # extract elements which are greater than 10 using boolen expression using as index
print('\n',e2[e2<=7]) #less than 7
print('\n',e2[(e2>10) & (e2<17)]) #greater than 10 and less than 17

#set the elements with a value that satisfies the boolean expression
e2[(e2>10) & (e2<17)] = -1
print('\n',e2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 [11 12 13 14 15 16 17 18 19 20 21 22 23 24]

 [0 1 2 3 4 5 6 7]

 [11 12 13 14 15 16]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [38]:
#set operations
f2 = np.array([1,2,3,4,5])
g2 = np.array([6,7,2,8,4])

print('intersection   :',np.intersect1d(f2,g2)) #common elements
print('set diifference:',np.setdiff1d(f2,g2))  #in first array but not in second array
print('union          :',np.union1d(f2,g2))    #all elements in both of the arrays

intersection   : [2 4]
set diifference: [1 3 5]
union          : [1 2 3 4 5 6 7 8]


In [50]:
#When sort is used as a function it sorts the numpy array out of place, meaning they don't change the original
#array. However when you use sort as a method the array is sorted in place, meaning the original array is changed.
h2 = np.random.randint(1,11,size=(10,))
print(h2)

[8 2 2 6 5 1 9 1 7 7]


In [51]:
print(np.sort(h2))  #h2 not changed
print(np.sort(np.unique(h2))) #sort with unique elements in h2
print(h2)
h2.sort() #h2 got changed and sort applied in place
print(h2)

[1 1 2 2 5 6 7 7 8 9]
[1 2 5 6 7 8 9]
[8 2 2 6 5 1 9 1 7 7]
[1 1 2 2 5 6 7 7 8 9]


In [52]:
i2 = np.random.randint(1,11,size=(5,5))
print(i2)

[[ 9  5 10  3  8]
 [ 9  5  5  9  2]
 [ 3  9  5  4  2]
 [ 4  2  6  7  8]
 [ 8  6  3  6  5]]


In [53]:
print(np.sort(i2,axis=0)) #sort on rows

[[ 3  2  3  3  2]
 [ 4  5  5  4  2]
 [ 8  5  5  6  5]
 [ 9  6  6  7  8]
 [ 9  9 10  9  8]]


In [54]:
print(np.sort(i2,axis=1)) #sort on columns

[[ 3  5  8  9 10]
 [ 2  5  5  9  9]
 [ 2  3  4  5  9]
 [ 2  4  6  7  8]
 [ 3  5  6  6  8]]


In [87]:
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape(5,5)
print(X)
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2==1]
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [76]:
#Arthimetic operations and Broadcasting
#Element wise operations -the arrays must be in same shape or broadcastable to apply these arthimetic operations
j2 = np.array([1,2,3,4,5])
k2 = np.array([6,7,8,9,10])
print('element wise sum',j2 + k2)
print('element wise sum',np.add(j2,k2))
print('element wise subtraction', j2 - k2)
print('element wise subtraction',np.subtract(j2,k2))
print('element wise multiplication',j2 * k2)
print('element wise multiplication',np.multiply(j2, k2))
print('element wise division', j2/k2)
print('element wise division',np.divide(j2,k2))
print('square root of each element', np.sqrt(j2)) #rank1 array
print('power of 2 ', np.power(k2, 2))
print('Exponential', np.exp(j2))

element wise sum [ 7  9 11 13 15]
element wise sum [ 7  9 11 13 15]
element wise subtraction [-5 -5 -5 -5 -5]
element wise subtraction [-5 -5 -5 -5 -5]
element wise multiplication [ 6 14 24 36 50]
element wise multiplication [ 6 14 24 36 50]
element wise division [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
element wise division [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
square root of each element [1.         1.41421356 1.73205081 2.         2.23606798]
power of 2  [ 36  49  64  81 100]
Exponential [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [68]:
#rank2 arrays
l2 = np.array([1,2,3,4]).reshape(2,2)
print(l2)
m2 = np.array([5,6,7,8]).reshape(2,2)
print(m2)
print('sum\n',l2+m2)
print('Subtraction\n', l2-m2)
print('product\n',l2*m2)
print('Division\n',l2/m2)
print('Average of all elements in l2:',l2.mean())
print('Average of all columns', l2.mean(axis=0))
print('Average of all rows', l2.mean(axis=1))
print('Sum of all',l2.sum())
print('sum of all columns',l2.sum(axis=0))
print('sum of all rows',l2.sum(axis=1))
print('Standard deviation',l2.std())
print('median', np.median(l2))
print('Max value',l2.max())
print('Min value', l2.min())

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
sum
 [[ 6  8]
 [10 12]]
Subtraction
 [[-4 -4]
 [-4 -4]]
product
 [[ 5 12]
 [21 32]]
Division
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Average of all elements in l2: 2.5
Average of all columns [2. 3.]
Average of all rows [1.5 3.5]
Sum of all 10
sum of all columns [4 6]
sum of all rows [3 7]
Standard deviation 1.118033988749895
median 2.5
Max value 4
Min value 1


In [70]:
#Add,ssubtract, multiply and divide all elements in an array with constant value
print(l2)
print('Add all elements with 3',l2 + 3)
print('Subtract all elements with 3',l2 - 3)
print('Multiply all elements with 3',l2 * 3)
print('Divide all elements with 3',l2/3)

[[1 2]
 [3 4]]
Add all elements with 3 [[4 5]
 [6 7]]
Subtract all elements with 3 [[-2 -1]
 [ 0  1]]
Multiply all elements with 3 [[ 3  6]
 [ 9 12]]
Divide all elements with 3 [[0.33333333 0.66666667]
 [1.         1.33333333]]


In [75]:
#broadcasting - numpy do the broadcasting on smaller array to make it compatible with the larger array for 
#arthiemtic operations
m2 = np.arange(9).reshape(3,3) #3 X 3 array
print(m2)
 
n2 = np.arange(3) #1 x 3 array
print(n2)

print(np.add(m2,n2)) #numpy broadcasts the smaller 1 X 3 array to 3 X 3 array . The smaller array can be expanded
#to fit with the larger array

o2 = np.arange(3).reshape(3,1)
print(o2)
print(m2 + o2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
[[0]
 [1]
 [2]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [88]:
# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 
X = np.ones((4,4)) * np.arange(1,5)
print(X)

Y = np.zeros((4,4)) + np.arange(1,5)
print(Y)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
